/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  kjdav
 * Created: 2017.10.27.
 */

/*USERS*/
INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');
INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (1, 0, 'kjdavid', 'kjdavid96@gmail.com', 'aaaaaa', 'USER');

/*SONGS*/
INSERT INTO SONGS (ID, VERSION, TITLE, ACCESS) VALUES (0, 0, 'Best Day Of My Life', 'PUBLIC');
INSERT INTO SONGS (ID, VERSION, TITLE, ACCESS) VALUES (1, 0, 'I''m Born To Run', 'PUBLIC');

/*TAGS*/
INSERT INTO TAGS (ID, VERSION, TAG) VALUES (0, 0, 'American Authors');
INSERT INTO TAGS (ID, VERSION, TAG) VALUES (1, 0, 'Oh, What a Life');
INSERT INTO TAGS (ID, VERSION, TAG) VALUES (2, 0, 'What We Live For');

/*SONGS_TAGS*/
INSERT INTO SONGS_TAGS (SONG_ID, TAGS_ID) VALUES (0, 0);
INSERT INTO SONGS_TAGS (SONG_ID, TAGS_ID) VALUES (0, 1);
INSERT INTO SONGS_TAGS (SONG_ID, TAGS_ID) VALUES (1, 0);
INSERT INTO SONGS_TAGS (SONG_ID, TAGS_ID) VALUES (1, 2);

/*RIGHTS*/
INSERT INTO RIGHTS (ID, VERSION, UID, SID, DELETE, SHARE, LISTEN) VALUES (0, 0, 0, 0, TRUE, TRUE, TRUE);
INSERT INTO RIGHTS (ID, VERSION, UID, SID, DELETE, SHARE, LISTEN) VALUES (1, 0, 0, 1, TRUE, TRUE, TRUE);
INSERT INTO RIGHTS (ID, VERSION, UID, SID, DELETE, SHARE, LISTEN) VALUES (2, 0, 1, 0, FALSE, FALSE, TRUE);
INSERT INTO RIGHTS (ID, VERSION, UID, SID, DELETE, SHARE, LISTEN) VALUES (3, 0, 1, 1, FALSE, FALSE, TRUE);

/*PLAYLISTS*/
INSERT INTO PLAYLISTS (ID, VERSION, NAME) VALUES (0, 0, 'Enyimé');
INSERT INTO PLAYLISTS (ID, VERSION, NAME) VALUES (1, 0, 'Másiké');
INSERT INTO PLAYLISTS (ID, VERSION, NAME) VALUES (2, 0, 'harmadiké');
INSERT INTO PLAYLISTS (ID, VERSION, NAME) VALUES (3, 0, 'harmadiké');

/*PLAYLISTS_SONGS*/
INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONGS_ID) VALUES (0, 0);
INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONGS_ID) VALUES (0, 1);
INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONGS_ID) VALUES (1, 0);
INSERT INTO PLAYLISTS_SONGS (PLAYLIST_ID, SONGS_ID) VALUES (1, 1);

/*USERS_PLAYLISTS*/
INSERT INTO USERS_PLAYLISTS (USER_ID, PLAYLISTS_ID) VALUES (0, 0);
INSERT INTO USERS_PLAYLISTS (USER_ID, PLAYLISTS_ID) VALUES (0, 1);
INSERT INTO USERS_PLAYLISTS (USER_ID, PLAYLISTS_ID) VALUES (1, 2);
INSERT INTO USERS_PLAYLISTS (USER_ID, PLAYLISTS_ID) VALUES (1, 3);

/*SELECT SONGS.TITLE, TAGS.TAG FROM SONGS, SONGS_TAGS, TAGS WHERE SONGS.ID=SONGS_TAGS.SONG_ID AND SONGS_TAGS.TAGS_ID=TAGS.ID*/